name: auto update extension ver

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run the download script
        run: python update_extensions.py

      - name: Commit and Push changes
        run: |
          # These lines "fake" a user identity for the commit
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          # The 'exit 0' prevents the script from failing if there are no new changes
          git commit -m "Automated update: Added new extension versions" || echo "No changes to commit"
          git push
